#默认使用配置
#开发配置
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test
    username: root
    password: admin
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    # 使用druid数据源
#公共配置与profiles选择无关
mybatis:
  typeAliasesPackage: com.demo.entity
  mapperLocations: classpath:mapper/*.xml



